ecommerceproject/ecommerceproject/cart/urls.py
from django.urls import path
from . import views
app_name='cart'
urlpatterns = [
    path('',views.cart_detail,name='cart_detail'),
    path('add/<int:id>/',views.add_cart,name='add_cart'),
    path('remove/<int:product_id>/',views.cart_remove, name='cart_remove'),
    path('remove/<int:product_id>/',views.full_remove, name='full_remove')
]

ecommerceproject/ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include('shop.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                           document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root = settings.MEDIA_ROOT)

ecommerceproject/ecommerceproject/search_app/urls.py
from django.urls import path
from . import views
app_name='search_app'
urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),
]

ecommerceproject/ecommerceproject/shop/urls.py
from . import views
from django.urls import path
app_name='shop'

urlpatterns = [
    path('', views.fn_allProdCat, name='fn_allProdCat'),
    path('<slug:c_slug>/', views.fn_allProdCat, name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.fn_productDetail, name='product_cat_Detail')
]

ecommerceproject/ecommerceproject/cart/models.py
from django.db import models
from shop.models import Product
# Create your models here.

class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self.product)

ecommerceproject/ecommerceproject/search_app/models.py
from django.db import models

# Create your models here.

ecommerceproject/ecommerceproject/shop/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250, unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category', blank=True)

    class Mata:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('shop:product_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='product'
        verbose_name_plural='products'

    def get_url(self):
        return reverse('shop:product_cat_Detail', args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.
def cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request,id):
    product=Product.objects.get(id=id)
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
    except Cart.DoesNotExist :
        cart=Cart.objects.create(
            cart_id=cart_id(request)
        )
        cart.save()
    try:
        cart_item=CartItem.objects.get(product=product,cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item=CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html', dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/ecommerceproject/search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
# Create your views here.

def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request, 'search.html', { 'query': query, 'products' : products })

ecommerceproject/ecommerceproject/shop/views.py
from django.shortcuts import render, get_object_or_404
from . models import Category,Product
from django.core.paginator import Paginator,EmptyPage,InvalidPage
# Create your views here.

def fn_allProdCat(request,c_slug=None):
    c_page=None
    product_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        product_list=Product.objects.all().filter(category=c_page, available=True)
    else:
        product_list = Product.objects.all().filter(available=True)
    paginator=Paginator(product_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except( EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)

    return render(request,'category.html',{'category':c_page, 'products':products})

def fn_productDetail(request,c_slug,product_slug):
    try:
        product=Product.objects.get(category__slug=c_slug,slug=product_slug)
    except Exception as err:
        raise err
    return render(request,'product.html', {'product': product})

ecommerceproject/ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
<div class="container-fluid container">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/propper.min.js' %}"></script>
</body>
</html>

ecommerceproject/ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
       Welcome to your cart. Proceed to review and place thr order.
{% endblock %}

{% block title %}
       CART - You & Me Shop
{% endblock %}

{% block content %}
    <div class="container">
        {% if not cart_items %}
        <div>
        <div class="text-center">
            <h1 class="text-center">Your Cart is Empty.</h1>
        </div>
        <br>
        <p class="text-center">
            Please Click <a href="{% url 'shop:fn_allProdCat' %}">Here</a>for continuing shopping.
        </p>
        </div>

        {% else %}
        <div>
            <div class="text-center">
                <h1 class="text-center">Your Cart Items</h1>
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 text-center">
                <table class="table custom_table">
                    <thead class="custom_thead">
                        <tr>
                            <th colspan="5" style="letter-spacing: 5px;">
                                Your Items
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td><br></td>
                    </tr>
                        {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <a href="cart_item.product.get_absolute_url"><img src="{{ cart_item.product.image.url }}" alt="" class="rounded float-left" width="100px" height="100px"></a>
                                </td>
                                <td class="text-left">
                                    {{ cart_item.product.name }}
                                    <br>
                                    Product ID : {{ cart_item.product.id }}
                                    <br>
                                    Price : {{ cart_item.product.price }} Rs/-
                                    <br>
                                    Qantity : {{ cart_item.quantity }} x {{ cart_item }}
                                </td>
                                <td>
                                    {{ cart_item.sub_total }} Rs/-
                                </td>
                                <td>
                                    {% if cart_item.quantity < cart_item.product.stock %}

                                        <a href="{% url 'cart:add_cart' cart_item.product.id %}">
                                            <i class="fas fa-plus"></i>
                                        </a>&nbsp;&nbsp;

                                        <a href="{% url 'cart:cart_remove' cart_item.product.id %}">
                                            <i class="fas fa-minus"></i>
                                        </a>&nbsp;&nbsp;
                                    <a href="{% url 'cart:full_remove' cart_item.product.id %}">
                                            <i class="fas fa-trash"></i>
                                        </a>&nbsp;&nbsp;
                                    {% else %}
                                        <a href="">
                                            <i class="fas fa-minus"></i>
                                        </a>&nbsp;&nbsp;
                                    <a href="">
                                            <i class="fas fa-trash"></i>
                                        </a>&nbsp;&nbsp;

                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>

                </table>
            </div>

        {% endif %}
        <div class="col-md-6 text-center">
            <table class=" table custom_table">
                <thead class="custom_thead">
                    <tr>
                        <th colspan="5" style="letter-spacing: 5px;">
                            Checkout
                        </th>
                     </tr>
                 </thead>
                <tbody>
                <tr>
                    <td><br></td>
                </tr>
                    <tr>
                        <td>
                            Please review your cart item before proceeding with order payment
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Your Total is : <strong>{{ total }}</strong>
                        </td>

                    </tr>
                </tbody>
            </table><br>
            <div>
                <a href="{% url 'shop:fn_allProdCat' %} " class="btn btn-secondary"> Continue Shopping</a>
            </div>
        </div>
        </div>
    </div>

{% endblock %}

ecommerceproject/ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {% if category %}
            {{category.description|truncatewords:155}}
        {% else %}
            Welcome to You & Me Shop for buying Items...
        {% endif %}
{% endblock %}

{% block title %}
        {% if category %}
            {{category.name}} - You & Me Store
        {% else %}
            See Our New Collection - You & Me Store
        {% endif %}
{% endblock %}

{% block content %}
    {% if category %}
    <div class="row">
        <div>
            <p> <a href="{% url 'shop:fn_allProdCat' %}">Our Product Collection</a> </p>
        </div>
    </div>
    {% endif %}

    <div>
        {% if category %}
        <img src="{{category.image.url}}" alt="{{category.name}}" width="1100px" height="300px" >
    </div>
    <div style="display: flex;">
        <h2>{{category.name}}</h2>
        <p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
    <div>
        <img class="rounded" src="{% static 'image/banner.png' %}" alt="our Products" width="1100px" height="300px" >
    </div>

    <div>
        <br>
    <h2 class="text-center">Our Products Collection</h2>
    <p class="text-justify">E-commerce is revolutionizing the way we all shop in India. Why do you want to hop from one store to another in search of the latest phone when you can find it on the Internet in a single click? Not only mobiles. You & Me Shop houses everything you can possibly imagine, from trending electronics like laptops, tablets, smartphones, and mobile accessories to in-vogue fashion staples like shoes, clothing and lifestyle accessories; from modern furniture like sofa sets, dining tables, and wardrobes to appliances that make your life easy like washing machines, TVs, ACs, mixer grinder juicers and other time-saving kitchen and small appliances; from home furnishings like cushion covers, mattresses and bedsheets to toys and musical instruments, we got them all covered. You name it, and you can stay assured about finding them all here. For those of you with erratic working hours, You & Me Shop is your best bet. Shop in your PJs, at night or in the wee hours of the morning. This e-commerce never shuts down.</p>
    </div>
    {% endif %}
<br>

<div class="container">
<div class="row">
        {% for product in products.object_list %}
            <div class="col-sm-4">
                <div class="card bg-light mb-3" style="max-width: 18rem;">
                 <a href="{{product.get_url}}">
                  <img src="{{product.image.url}}" alt="{{product.name}}" class="card-img-top">
                 </a>
                  <div class="card-body">
                    <h5 class="card-title">{{product.name}}</h5>
                    <p class="card-text">{{ product.price}} Rs</p>
                  </div>
                </div>
            </div>
        {% endfor %}
</div>
<!--    paginator number-->
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

ecommerceproject/ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class="text-center">&copy; You & Me Shop Pvt Ltd. All Rights Reserved</p>
</div>

ecommerceproject/ecommerceproject/templates/header.html
{% load static %}
<div>
    <center>
        <a href="{% url 'shop:fn_allProdCat' %}">
            <img src="{% static 'image/logo.png' %}" alt="logoimg" width="150px" height="130px">
        </a>
    </center>

</div>

ecommerceproject/ecommerceproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:fn_allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} activate {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:fn_allProdCat' %}">All Products</a></li>
            {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}"><i class="fa fa-shopping-cart " style="cursor: pointer;">{{ item_count }}</i></a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">
          <i class="fa fa-search"></i>
        </button>
      </form>
    </div>
  </div>
</nav>
<br>


<!--<nav>-->
<!--  <li> <a href="{% url 'shop:fn_allProdCat' %}">All Products</a> </li>-->
<!--  {% for cat in links %}-->
<!--  <li><a href="{{cat.get_url}}">{{cat.name}}</a> </li>-->
<!--  {% endfor %}-->
<!--  <li>yor cart()</li>-->
<!--</nav>-->

ecommerceproject/ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
            {{product.description|truncatewords:155}}
{% endblock %}

{% block title %}
        {% if category %}
            {{product.name}}
        {% endif %}
{% endblock %}

{% block content %}

<div>
    <div>
        <p><a href="{% url 'shop:fn_allProdCat' %}">Home</a>|
            <a href="{{product.category.get_url}}">{{product.category}}</a>|
            {{product.name}}
        </p>
    </div>
</div>
<br>

<div class="row">
    <div class="col-12 col-md-8">
        <div>
            <img src="{{product.image.url}}" alt="{{product.name}}" width="500px" height="300px">
        </div>
    </div>
    <div class="col-6 col-md-4">
        <br>
        <h1>{{product.name}}</h1>
        <p>{{product.price}} Rs</p>
        <p>Product Description</p>
        <p>{{product.description}}</p>

        {% if product.stock <= 0 %}
            <p><b>Out of Stock</b></p>
        {% else %}
            <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-primary"><i class="fa fa-cart-plus"></i> &nbsp; Add to Cart</a>
        {% endif %}
    </div>
</div>
<br>

{% endblock %}

ecommerceproject/ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have variety of products..
{% endblock %}

{% block title %}
       Search
{% endblock %}

{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for : <b>"{{query}}"</b> </p>
</div>
<div class="container">
<div class="row">
        {% for product in products %}
            <div class="col-sm-4">
                <div class="card" style="width: 18rem;">
                 <a href="{{product.get_url}}">
                  <img src="{{product.image.url}}" alt="{{product.name}}" class="card-img-top">
                 </a>
                  <div class="card-body">
                    <h5 class="card-title">{{product.name}}</h5>
                    <p class="card-text">{{ product.price}} Rs</p>
                  </div>
                </div>
            </div>
        {% empty %}
            <div class="row">
                <p class="text-center my_search_text">0 results found</p>
            </div>
        {% endfor %}
</div>
</div>

{% endblock %}